### PR TITLE
remove send element of FiFo

### PR DESCRIPTION
**Pull request by JochiSt**
if message is send, remove it from FiFo. This gives space for next message, which can be send. Otherwise the FiFo is blocked and only the first message is send.

### CODE REVIEW

**Comment by fishpepper** [comment]
thanks for your feedback!

**Comment by EmbedME** [comment]
This leads to an error:
`File "pyusbtin/usbtin.py", line 296, in rx_thread
self.tx_fifo.pop(0)
IndexError: pop from empty list`

The message is removed from the Fifo once the USBtin has accepted the message ('z'):
https://github.com/fishpepper/pyUSBtin/blob/master/pyusbtin/usbtin.py#L296

**Comment by fishpepper** [comment]
I do not have the hardware to test. but if i dig deeper in the code, it looks like the pop in this pr breaks the functionality and the previous version was correct, right? The message should be only popped when the usbtin requests the removal.

**Comment by EmbedME** [comment]
Yes, I think the previous version was correct - it runs without problems, the messages are sent correctly one after the other from the fifo.

If you need hardware for testing, please contact me.

**Comment by fishpepper** [comment]
ok i will revert it. Hw: Thanks for the offer! I still have my pyusbtin but I do no longer have the can bus hardware I used for testing and development ;)

**Pull request merged**
